// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoTnQ6WmXOJfHj2D8m0HW8x7qhS-OLEHU',
    appId: '1:107265527466:web:c807198baad693a9efcad3',
    messagingSenderId: '107265527466',
    projectId: 'todolist-a7cde',
    authDomain: 'todolist-a7cde.firebaseapp.com',
    storageBucket: 'todolist-a7cde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG2aihsvND5hl5BU6Hx48zwtwv57poqfI',
    appId: '1:107265527466:android:13fe2792e0fdef25efcad3',
    messagingSenderId: '107265527466',
    projectId: 'todolist-a7cde',
    storageBucket: 'todolist-a7cde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEav0BEgtlxGD-h5lmrJVaaCPEhVKIRaE',
    appId: '1:107265527466:ios:ffdfccb1a12b7635efcad3',
    messagingSenderId: '107265527466',
    projectId: 'todolist-a7cde',
    storageBucket: 'todolist-a7cde.appspot.com',
    iosBundleId: 'com.example.todolist',
  );
}
